### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by skybarberom** [MountainGod2/chaturbate_poller#12]
I tried to run the new docker image, but I get into authorization error for your URL

```
Traceback (most recent call last):
  File "/venv/lib/python3.11/site-packages/chaturbate_poller/chaturbate_client.py", line 164, in fetch_events
    response.raise_for_status()
  File "/venv/lib/python3.11/site-packages/httpx/_models.py", line 761, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '401 Unauthorized' for url 'https://events.testbed.cb.dev/events/XXXX/XXXXXX/?timeout=10'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/40
```

If I launch your URL in the browser I get also 401, If I launch the events URL from CB I get some datas back correctly

**Comment by MountainGod2** [comment]
Sorry, I forgot to respond to this. Unfortunately, the CB events API testbed is still as flaky as ever.

In the interim, I've tried to improve the logging / provide more meaningful tracebacks, but without a reliable and stable endpoint on their end, troubleshooting things like this still remains a bit of a lost cause I'm afraid.
